name: Daily Logo Cleanup
on:
  schedule:
    - cron: '0 3 * * *' # Ogni giorno alle 05:00 UTC
  workflow_dispatch:
jobs:
  cleanup-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Installazione di tutte le dipendenze necessarie
      - name: Install system dependencies
        run: |
          sudo apt-get update

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests python-dotenv

      - name: Rimuovi file nella cartella logs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd logos
          git rm -r .
          git add .
          git commit -m "Pulizia log automatica [skip ci]"
          git push
